####
# Basic Website Details
####
title: "PCS HMRC Rank & File Network"
short-title: "Rank & File Network"
author: "PCS HMRC Rank & File Network"
description: "The PCS HMRC Rank & File Network is a new initiative from activists in R&C Group who believe the union needs to reconnect with its members to be more effective in fighting to defend and improve our pay and conditions."

email: hello@pcsrankandfile.com

####
# Navigation Menu:
#  - To customise the navigation menu, edit the "menu.csv" in the "_data" folder. 
####

####
# Homepage Settings:
#  - Homepage image splash secion
####
home-splash: true #Change to 'false' to disable. 
home-splash-heading: "HMRC Rank & File Network"
home-splash-subheading: "Campaigning for a better union"

####
# Homepage Settings:
#  - Homepage 'Call To Action' secion
####
home-cta: true #Change to 'false' to disable. 
home-cta-text: "We're standing for the GEC"
home-cta-link: "/elections"
home-cta-link-text: "Nominate!"

####
# Footer Settings:
#  - Text to display in the footer
####
footer-text: "PCS Revenue & Customs Rank and File Netwok."


####
# Website Design:
#  - Defult Images (These are shared on social media & in browser menus)
####
social-media-image: "/assets/site/images/400x400.jpg"
touch: "/assets/site/images/touch.png"
logo-favicon-small: "/assets/site/images/favicon-16x16.png"
logo-favicon-medium: "/assets/site/images/favicon-32x32.png"
logo-favicon-large: "/assets/site/images/favicon-96x96.png"

####
# Website Design:
#  - Pinned Colour is used by android(ect)
####
pinned-colour: "#EE4035"

####
# Social Media
#  - Settings for social media (remove # to use)
####
#facebook-app-id: "..." # For Facebook OpenGraph integration
#facebook-profile-id: "..." # For Facebook OpenGraph integration
#facebook-admin-id: "..." # For Facebook OpenGraph integration
facebook-url:	"https://facebook.com/pcsrankandfile"
facebook-handle: "pcsrankandfile"

twitter-url: "https://twitter.com/pcsrankandfile"
twitter-handle: "pcsrankandfile"

github-url:  "https://github.com/pcsrankandfile"
github-handle:  "pcsrankandfile"

####
# Google
#  - Settings for Google Analytics (remove # to use)
####
#google-site-verification: ""
#google-analytics: ""


####
# Collections:
#  - Post/News settings (ect)
####
permalink: /news/:year/:month/:day/:title:output_ext


####
# Build Settings
####
url: "http://pcsrankandfile.com"
baseurl: ""
markdown: kramdown