####
# Basic Website Details
####
title: "PCS Rank & File Network"
short-title: "Rank & File Network"
author: "PCS Rank & File Network"
description: "The PCS Rank & File Network is a new initiative from activists in R&C Group who believe the union needs to reconnect with its members to be more effective in fighting to defend and improve our pay and conditions."

email: hello@pcsrankandfile.com

####
# Navigation Menu:
#  - To customise the navigation menu, edit the "menu.csv" in the "_data" folder. 
####

####
# Homepage Settings:
#  - Homepage image splash secion
####
home-splash: true #Change to 'false' to disable. 
home-splash-heading: "Rank & File Network"
home-splash-subheading: "Campaigning for a better union"

####
# Homepage Settings:
#  - Homepage 'Call To Action' secion
####
home-cta: true #Change to 'false' to disable. 
home-cta-text: "Help us build the rank and file movement. "
home-cta-link: "https://pcsrankandfile.us20.list-manage.com/subscribe?u=02fb4405bc5e114328b0d2815&id=f6314cced8" 
home-cta-link-text: "Join Us"

####
# Footer Settings:
#  - Text to display in the footer
####
footer-text: "PCS Rank and File Network. "


####
# Website Design:
#  - Defult Images (These are shared on social media & in browser menus)
####
social-media-image: "/assets/site/images/400x400.jpg"
touch: "/assets/site/images/touch.png"
logo-favicon-small: "/assets/site/images/favicon-16x16.png"
logo-favicon-medium: "/assets/site/images/favicon-32x32.png"
logo-favicon-large: "/assets/site/images/favicon-96x96.png"

####
# Website Design:
#  - Pinned Colour is used by android(ect)
####
pinned-colour: "#EE4035"

####
# Social Media
#  - Settings for social media (remove # to use)
####
#facebook-app-id: "..." # For Facebook OpenGraph integration
#facebook-profile-id: "..." # For Facebook OpenGraph integration
#facebook-admin-id: "..." # For Facebook OpenGraph integration
facebook-url:	"https://facebook.com/pcsrankandfile"
facebook-handle: "pcsrankandfile"

twitter-url: "https://twitter.com/pcsrankandfile"
twitter-handle: "pcsrankandfile"

github-url:  "https://github.com/pcsrankandfile"
github-handle:  "pcsrankandfile"

####
# Google
#  - Settings for Google Analytics (remove # to use)
####
#google-site-verification: ""
#google-analytics: ""


####
# Collections:
#  - Post/News settings (ect)
####
permalink: /news/:year/:month/:day/:title:output_ext


####
# Build Settings
####
url: "https://pcsrankandfile.com"
baseurl: ""
markdown: kramdown
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

####
# https://prose.io/
####
prose:
  siteurl: 'https://pcsrankandfile.com/'
  media: 'assets/images'
  ignore:
  - .gitattributes
  - .gitignore
  - 404.html
  - CNAME
  - README.md
  - _config.yml
  - /join-us
  - /_layouts
  - /_includes
  - index.md
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"    
      - name: "regions"
        field:
          element: "multiselect"
          label: "Add regions this post applies to"
          placeholder: "Choose Tags"
          options:
            - name: "Northern Ireland"
              value: "northernireland"
            - name: "Scotland"
              value: "scotland"
            - name: "Wales"
              value: "wales"
            - name: "East of England"
              value: "eastofengland"
            - name: "East Midlands"
              value: "eastmidlands"
            - name: "West Midlands"
              value: "westmidlands"
            - name: "London"
              value: "london"
            - name: "North East"
              value: "northeast"
            - name: "North West"
              value: "northwest"
            - name: "South East"
              value: "southeast"
            - name: "South West"
              value: "southwest"
            - name: "Yorkshire and Humber"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Post title"
          placeholder: "Enter your post title here"
      - name: "author"
        field:
          element: "text"
          type: "text"
          value: "Rank & File Network"
          label: "Author"
      - name: "date"
        field:
          element: "text"
          type: "text"
          value: "2000-01-01"
          label: "Post date"
          placeholder: "2000-01-01"
      - name: "permalink"
        field:
          element: "text"
          type: "text"
          label: "Permalink"
          placeholder: "news/2018/01/01/name-of-post"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
          placeholder: "Enter the short summary for the post here."
      - name: "published"
        field: 
          element: "checkbox"
          label: "Publish post?"
          value: true
